### ISSUE TITLE
Crash when adding new devices

### ISSUE THREAD

**Issue by shaw-iot** [Achronite/energenie-ener314rt#15]
After running for a few hours, adding new devices will cause the error message "Something went wrong discovering OpenThings devices" to appear. Node-RED will then restart and devices can be added as normal. Running with Node-RED v1.2.9 and node-red-contrib-energenie-ener314rt v0.3.9. Running on a Pi2 with 1GB RAM, plenty free at the time of the crashes.

Feb 17 18:38:31 ntp0 systemd[1]: nodered.service: Main process exited, code=killed, status=11/SEGV
Feb 17 18:38:31 ntp0 systemd[1]: nodered.service: Failed with result 'signal'.
Feb 17 18:38:51 ntp0 systemd[1]: nodered.service: Service RestartSec=20s expired, scheduling restart.
Feb 17 18:38:51 ntp0 systemd[1]: nodered.service: Scheduled restart job, restart counter is at 1.
Feb 17 18:38:51 ntp0 systemd[1]: Stopped Node-RED graphical event wiring tool.
Feb 17 18:38:51 ntp0 systemd[1]: Started Node-RED graphical event wiring tool.

**Comment by shaw-iot** [comment]
That would certainly explain why it takes a while before it starts to crash. Straight after loading the number of devices is small and it takes a while for them to build up. I'm using 0.3.9 from the built-in "Manage palette", but I can either manually apply the patch or figure out how to run with v4.

**Comment by Achronite** [comment]
I've applied the fix to the 'develop' branch; but the signature of the function has changed, so I'm not planning on back-porting it to v0.3.x.

By the way, v0.4.x has new nodes for specific devices - I've done ones for the PIR and Themostat so far; I'm planning on one for the door sensor too now as I have your messages.  Does it send '0' for Open and '1' for closed in DOOR_SENSOR?

**Comment by shaw-iot** [comment]
Yes, that's what it appears to send (1=OPEN, 0=CLOSED). Below is a trace of opening and closing the door. I've left the home energy data in there in case it's useful and so you can see the timestamps of events as they are received.
(btw, this is with the 50ms sleep I left in the code from testing yesterday)

```
openThings_receive(): rec:1 {"name":"VOLTAGE","id":118,"type":2,"str":"","int":976,"float":3.812500}
openThings_receive(): rec:2 {"name":"CURRENT","id":105,"type":2,"str":"","int":407,"float":1.589844}
openThings_receive: Returning: {"deviceId":6409,"mfrId":4,"productId":5,"timestamp":1613753223,"APPARENT_POWER":446,"VOLTAGE":3.812500,"CURRENT":1.589844}
********************************************************************************************************************************************@
openThings_receive(): rec:0 {"name":"DOOR_SENSOR","id":100,"type":1,"str":"","int":1,"float":1.000000}
openThings_receive: Returning: {"deviceId":7314,"mfrId":4,"productId":13,"timestamp":1613753230,"DOOR_SENSOR":1}
*@
openThings_receive(): rec:0 {"name":"DOOR_SENSOR","id":100,"type":1,"str":"","int":1,"float":1.000000}
openThings_receive: Returning: {"deviceId":7314,"mfrId":4,"productId":13,"timestamp":1613753230,"DOOR_SENSOR":1}
*****************************************************@
openThings_receive(): rec:0 {"name":"DOOR_SENSOR","id":100,"type":1,"str":"","int":0,"float":0.000000}
openThings_receive: Returning: {"deviceId":7314,"mfrId":4,"productId":13,"timestamp":1613753233,"DOOR_SENSOR":0}
*@
openThings_receive(): rec:0 {"name":"DOOR_SENSOR","id":100,"type":1,"str":"","int":0,"float":0.000000}
openThings_receive: Returning: {"deviceId":7314,"mfrId":4,"productId":13,"timestamp":1613753233,"DOOR_SENSOR":0}
*****@
openThings_receive(): rec:0 {"name":"APPARENT_POWER","id":80,"type":1,"str":"","int":477,"float":477.000000}
openThings_receive(): rec:1 {"name":"VOLTAGE","id":118,"type":2,"str":"","int":976,"float":3.812500}
openThings_receive(): rec:2 {"name":"CURRENT","id":105,"type":2,"str":"","int":435,"float":1.699219}
openThings_receive: Returning: {"deviceId":6409,"mfrId":4,"productId":5,"timestamp":1613753233,"APPARENT_POWER":477,"VOLTAGE":3.812500,"CURRENT":1.699219}
************************************************************************************************************************************************************************************************************@
openThings_receive(): rec:0 {"name":"APPARENT_POWER","id":80,"type":1,"str":"","int":463,"float":463.000000}
openThings_receive(): rec:1 {"name":"VOLTAGE","id":118,"type":2,"str":"","int":976,"float":3.812500}
openThings_receive(): rec:2 {"name":"CURRENT","id":105,"type":2,"str":"","int":423,"float":1.652344}
openThings_receive: Returning: {"deviceId":6409,"mfrId":4,"productId":5,"timestamp":1613753244,"APPARENT_POWER":463,"VOLTAGE":3.812500,"CURRENT":1.652344}
```

**Comment by Achronite** [comment]
Thank you, I've added the new open sensor node to the develop branch of node-red-contrib-energenie-ener314rt.

I'll aim to release the packages for this (and the dependent node module) in the next couple of days.

**Comment by shaw-iot** [comment]
This is now working OK for me (7 devices), thanks.
