### ISSUE TITLE
Create MQTT Implementation

### ISSUE THREAD

**Issue by Achronite** [Achronite/energenie-ener314rt#22]
Create a new stand-alone node.js app that wraps the functionality of this repo and uses MQTT as the interface method.

The primary aim would be to support Home Assistant, but other servers could utilize this as well.

**Comment by GiantCheesepuff** [comment]
Hey, I'm really interested in this addition. I'm very new to the whole home automation and Home Assistant stuff (and GitHub). We've got Energenie switches that i'd love to convert to locally controlled with HA integration :)

Glad to help and test if need be although not sure how much help i'd be with development.

**Comment by Achronite** [comment]
I don't know much about Home Assistant.  @GiantCheesepuff Are you able to help with the topic design for MQTT?  I was thinking along these lines:

**UPDATED: 2/1/2023**

|device|command topic|state topic|other topics...|
|---|---|---|---|
|ook-switch|energenie/ook/*zone*/*switchNum*/command|energenie/ook/*zone*/*switchNum*/state|n/a|
|openThings-switch|energenie/2/*deviceNum*/switch/command|energenie/2/*deviceNum*/switch/state|energenie/2/*deviceNum*/REAL_POWER/state|
|openThings-monitor|n/a|energenie/5/*deviceNum*/switch/state|energenie/5/*deviceNum*/APPARENT_POWER/state|
|openThings-pir|n/a|energenie/12/*deviceNum*/motion/state|n/a|

**Comment by Achronite** [comment]
@GiantCheesepuff What devices do you own?  Are they just dump switches (ENER002/equiv)?

**Comment by Achronite** [comment]
Alpha version now available at https://github.com/Achronite/mqtt-energenie-ener314rt

**Comment by genestealer** [comment]
Hey guys, just so you know, I have been working on MQTT integration for home assistant for a few weeks using the MQTT Auto Discovery. Happy to collaborate. Using the auto discovery, you don't have to set up anything in home assistant apart from enabling MQTT, It's the same design philosophy as Zigbee2MQTT.

**Comment by genestealer** [comment]
I have, eTRV's, plug-in sockets switches, dual and single light switches and dimmable light switches.

**Comment by Achronite** [comment]
Please let me know the details.  I'm new to Home Assistant, but from what I've read, it is all about how you design the MQTT topic structure.

You can send me yours flows.json from node-red if that's easier.

**Comment by genestealer** [comment]
I am publishing it on GitHub, will post the link soon, just cleaning the code up.

Looks like this:
![image](https://user-images.githubusercontent.com/5207490/211163631-8221f711-7bf8-4939-8081-375b02a50530.png)
![image](https://user-images.githubusercontent.com/5207490/211163638-10bf7665-6bce-4180-89d0-5b4858b122ea.png)
![image](https://user-images.githubusercontent.com/5207490/211163647-34045caf-4e8b-4d23-8306-7cc17271dd7b.png)
![image](https://user-images.githubusercontent.com/5207490/211163661-bc554ad2-7d2f-4259-b4bb-a67763c6e838.png)
![image](https://user-images.githubusercontent.com/5207490/211163667-2c8a695d-21f9-467a-a4a9-ea524b52f654.png)
![image](https://user-images.githubusercontent.com/5207490/211163677-8b961f96-7e15-4540-9875-da064cc07ef0.png)

Also works for plugs and plugs+
![image](https://user-images.githubusercontent.com/5207490/211163748-55767cc5-bb0e-41ed-b397-9c38ece7b760.png)
![image](https://user-images.githubusercontent.com/5207490/211163768-617a881f-dea0-4019-bf98-2acda5b27015.png)

![image](https://user-images.githubusercontent.com/5207490/211163797-70e2fd0a-c8e9-492a-98c7-c2d5979024eb.png)
![image](https://user-images.githubusercontent.com/5207490/211163800-0f5c9403-5b60-436a-ac88-e019c3cffd87.png)

**Comment by genestealer** [comment]
Work in progress version: https://github.com/genestealer/node-red-energenie-ener314rt-home-assistant-mqtt

Feedback very welcome!
![image](https://user-images.githubusercontent.com/5207490/211171674-926b6792-e80f-4866-a234-a3e895df1f17.png)

**Comment by Achronite** [comment]
Stable alpha version now available on github. https://github.com/Achronite/mqtt-energenie-ener314rt
